/* eslint-disable no-dupe-keys */
import {StyleSheet, Dimensions} from 'react-native';
import Theme from '../../Utils/Theme';

const styles = StyleSheet.create({
  MainView: {
    flex: 1,
  },
  header: {
    backgroundColor: '#FFFFFF',
    shadowColor: '#333333',
    shadowOffset: {width: -1, height: -3},
    shadowRadius: 2,
    shadowOpacity: 0.4,
    // elevation: 5,
    paddingTop: 10,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  panelHeader: {
    alignItems: 'center',
  },

  panelButton: {
    padding: 13,
    borderRadius: 10,
    backgroundColor: Theme.primary,
    alignSelf: 'center',
    marginVertical: 7,
    alignItems: 'center',
    position: 'absolute',
    width: '70%',
    bottom: 0,
  },
  wrapPlusBtn: {
    backgroundColor: Theme.primary,
    width: Theme.wp('15%'),
    height: Theme.wp('15%'),
    borderRadius: 90,
    alignItems: Theme.align,
    justifyContent: Theme.align,
    position: 'absolute',
    bottom: '25%',
    right: '5%',
  },
  header: {
    backgroundColor: '#FFFFFF',
    shadowColor: '#333333',
    shadowOffset: {width: -1, height: -3},
    shadowRadius: 2,
    shadowOpacity: 0.4,
    // elevation: 5,
    paddingTop: 20,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  panel: {
    backgroundColor: '#fff',
    padding: '3%',
  },
  imgMarker: {
    width: 10,
    height: 20,
    marginTop: '10%',
    marginLeft: '30%',
  },
  txtTitle: {
    fontSize: 18,
    color: '#000000',
    fontWeight: '500',
  },
  txtCreatedBy: {
    fontSize: 20,
    fontWeight: '600',
  },
  txtPosts: {
    // color: '#959494',
    color: 'white',
    fontSize: 16,
    fontWeight: '500',
    marginTop: '5%',
  },
  // modalWrapper: {
  //   backgroundColor: 'white',
  //   borderRadius: 30,
  //   elevation: 4,
  //   height: '10%',
  //   marginTop: '15%',
  // },
  heading: {
    alignSelf: 'center',
    top: 20,
    color: 'black',
    fontSize: 20,
    fontWeight: 'bold',
  },
  boxWrap: {
    backgroundColor: '#2196F3',
    height: '25%',
    width: '100%',
    marginTop: '5%',
    opacity: 0.5,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: '3%',
    borderRadius: 5,
  },
  txtStatus: {
    color: '#000',
    fontWeight: '600',
    fontSize: 16,
  },
  ImgPin: {
    height: 20,
    width: 20,
  },
  btnNavigate: {
    alignItems: 'center',
    justifyContent: 'center',
    height: '15%',
    width: '100%',
    backgroundColor: '#1596F3',
    borderRadius: 5,
    bottom: '9%',
    // marginTop: '5%',
  },
  txtNavigate: {
    color: '#fff',
    fontWeight: '600',
    fontSize: 16,
  },
  addpostBtn: {
    alignSelf: 'flex-start',
    fontSize: 20,
    marginTop: 10,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: '#1596F3',
    backgroundColor: Theme.primary,
    padding: 7,
    marginBottom: 20,
    elevation: 3,
    width: '42%',
    color: '#1596F3',
  },
  cancelBtn: {
    alignSelf: 'flex-start',
    fontSize: 20,
    marginTop: 10,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: '#1596F3',
    backgroundColor: Theme.white,
    padding: 7,
    marginBottom: 20,
    elevation: 3,
    width: '42%',
    color: '#1596F3',
  },
  addquiz: {
    alignSelf: 'flex-start',
    fontSize: 20,
    marginTop: 10,

    padding: 7,
    color: '#1596F3',
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 10,
  },
  option: {
    color: 'black',
    alignSelf: 'flex-start',
    fontSize: 17,
  },
  markerin: {
    width: '100%',
    height: 100,
    color: 'white',
    fontSize: 16,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#e1e1e1',
    backgroundColor: '#66B5EB',
    marginBottom: 17,
  },
  heading2: {
    color: 'black',
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: '4%',
  },
  markerTxin: {
    width: '100%',
    color: 'white',
    fontSize: 16,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: '#e1e1e1',
    backgroundColor: '#66B5EB',
    marginBottom: 17,
  },
  modalWrapper: {
    backgroundColor: 'white',
    borderRadius: 15,
    marginTop: '15%',
  },
  arrivedBtn: {
    alignSelf: 'center',
    fontSize: 20,
    marginBottom: 20,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: '#1596F3',
    backgroundColor: Theme.primary,

    padding: 7,
    marginTop: 20,
    elevation: 3,
    // width: '42%',
    color: '#1596F3',
  },
  value: {
    fontSize: 17,
    color: 'red',
  },
  headingName: {
    alignSelf: 'flex-start',
    marginTop: '10%',
    marginBottom: '3%',
    color: 'black',
    fontSize: 20,
    fontWeight: 'bold',
  },
  crossButton: {
    // padding: 13,
    margin: 20,
    borderRadius: 10,
    backgroundColor: Theme.primary,
    alignSelf: 'flex-end',
    marginVertical: 7,
    alignItems: 'center',
  },
  panelButtonTitle: {
    fontSize: 17,
    fontWeight: 'bold',
    color: 'white',
  },
});

export default styles;
